version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 2
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
